### ISSUE TITLE
Pagination issue for queue

### ISSUE THREAD

**Issue by kafisatz** [TrimVis/butlarr#12]
My queue currently results in 10 pages in telegram.
After page 3, I tend to run into the following error which I wanted to report here.
<img width="1202" alt="image" src="https://github.com/TrimVis/butlarr/assets/15026865/577067f5-c7fc-4168-b0f4-52f69e436db6">

**Comment by TrimVis** [comment]
Thanks for the report, I will look into it :)

**Comment by TrimVis** [comment]
@kafisatz 
I just deployed some fixes for it, could you please pull and try again? :)

**Comment by kafisatz** [comment]
Thanks.
This works better now.

Sometimes I still get an error message. But I think this may be related to a timing issue (when I click 'next page' too fast).
I think it is generally working now.

See below for some details. 


```
butlarr  | 2024-06-19 08:43:30.113 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '12']
butlarr  | 2024-06-19 08:43:30.114 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:30.114 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:30.114 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:30.114 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:30.260 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '12']
butlarr  | 2024-06-19 08:43:30.261 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:30.261 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:30.262 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:30.262 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | No error handlers are registered, logging exception.
butlarr  | Traceback (most recent call last):
butlarr  |   File "/app/butlarr/tg_handler/message.py", line 61, in wrapped_func
butlarr  |     await update.callback_query.edit_message_caption(
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_callbackquery.py", line 332, in edit_message_caption
butlarr  |     return await self._get_message().edit_caption(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_message.py", line 3646, in edit_caption
butlarr  |     return await self.get_bot().edit_message_caption(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1522, in edit_message_caption
butlarr  |     return await super().edit_message_caption(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 4099, in edit_message_caption
butlarr  |     return await self._send_message(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 608, in _send_message
butlarr  |     result = await super()._send_message(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 740, in _send_message
butlarr  |     result = await self._post(
butlarr  |              ^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 618, in _post
butlarr  |     return await self._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
butlarr  |     return await super()._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 647, in _do_post
butlarr  |     result = await request.post(
butlarr  |              ^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
butlarr  |     result = await self._request_wrapper(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
butlarr  |     raise BadRequest(message)
butlarr  | telegram.error.BadRequest: There is no caption in the message to edit
butlarr  |
butlarr  | During handling of the above exception, another exception occurred:
butlarr  |
butlarr  | Traceback (most recent call last):
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1325, in process_update
butlarr  |     await coroutine
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
butlarr  |     return await self.callback(update, context)
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/app/butlarr/tg_handler/__init__.py", line 77, in handler
butlarr  |     return await s.handle_callback(update, context)
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/app/butlarr/tg_handler/__init__.py", line 195, in handle_callback
butlarr  |     await c(self, update, context, args[1:])
butlarr  |   File "/app/butlarr/tg_handler/message.py", line 68, in wrapped_func
butlarr  |     await update.callback_query.edit_message_text(
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_callbackquery.py", line 264, in edit_message_text
butlarr  |     return await self._get_message().edit_text(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_message.py", line 3596, in edit_text
butlarr  |     return await self.get_bot().edit_message_text(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1651, in edit_message_text
butlarr  |     return await super().edit_message_text(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 4026, in edit_message_text
butlarr  |     return await self._send_message(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 608, in _send_message
butlarr  |     result = await super()._send_message(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 740, in _send_message
butlarr  |     result = await self._post(
butlarr  |              ^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 618, in _post
butlarr  |     return await self._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
butlarr  |     return await super()._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 647, in _do_post
butlarr  |     result = await request.post(
butlarr  |              ^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
butlarr  |     result = await self._request_wrapper(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
butlarr  |     raise BadRequest(message)
butlarr  | telegram.error.BadRequest: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
butlarr  | 2024-06-19 08:43:30.758 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '11']
butlarr  | 2024-06-19 08:43:30.758 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:30.758 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:30.758 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:30.758 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:31.067 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '13']
butlarr  | 2024-06-19 08:43:31.067 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:31.067 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:31.067 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:31.068 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:36.184 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '12']
butlarr  | 2024-06-19 08:43:36.185 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:36.185 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:36.186 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:36.187 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:36.306 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '12']
butlarr  | 2024-06-19 08:43:36.306 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:36.307 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:36.307 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:36.307 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | No error handlers are registered, logging exception.
butlarr  | Traceback (most recent call last):
butlarr  |   File "/app/butlarr/tg_handler/message.py", line 61, in wrapped_func
butlarr  |     await update.callback_query.edit_message_caption(
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_callbackquery.py", line 332, in edit_message_caption
butlarr  |     return await self._get_message().edit_caption(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_message.py", line 3646, in edit_caption
butlarr  |     return await self.get_bot().edit_message_caption(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1522, in edit_message_caption
butlarr  |     return await super().edit_message_caption(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 4099, in edit_message_caption
butlarr  |     return await self._send_message(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 608, in _send_message
butlarr  |     result = await super()._send_message(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 740, in _send_message
butlarr  |     result = await self._post(
butlarr  |              ^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 618, in _post
butlarr  |     return await self._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
butlarr  |     return await super()._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 647, in _do_post
butlarr  |     result = await request.post(
butlarr  |              ^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
butlarr  |     result = await self._request_wrapper(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
butlarr  |     raise BadRequest(message)
butlarr  | telegram.error.BadRequest: There is no caption in the message to edit
butlarr  |
butlarr  | During handling of the above exception, another exception occurred:
butlarr  |
butlarr  | Traceback (most recent call last):
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1325, in process_update
butlarr  |     await coroutine
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
butlarr  |     return await self.callback(update, context)
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/app/butlarr/tg_handler/__init__.py", line 77, in handler
butlarr  |     return await s.handle_callback(update, context)
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/app/butlarr/tg_handler/__init__.py", line 195, in handle_callback
butlarr  |     await c(self, update, context, args[1:])
butlarr  |   File "/app/butlarr/tg_handler/message.py", line 68, in wrapped_func
butlarr  |     await update.callback_query.edit_message_text(
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_callbackquery.py", line 264, in edit_message_text
butlarr  |     return await self._get_message().edit_text(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_message.py", line 3596, in edit_text
butlarr  |     return await self.get_bot().edit_message_text(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1651, in edit_message_text
butlarr  |     return await super().edit_message_text(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 4026, in edit_message_text
butlarr  |     return await self._send_message(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 608, in _send_message
butlarr  |     result = await super()._send_message(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 740, in _send_message
butlarr  |     result = await self._post(
butlarr  |              ^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 618, in _post
butlarr  |     return await self._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
butlarr  |     return await super()._do_post(
butlarr  |            ^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 647, in _do_post
butlarr  |     result = await request.post(
butlarr  |              ^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
butlarr  |     result = await self._request_wrapper(
butlarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
butlarr  |   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
butlarr  |     raise BadRequest(message)
butlarr  | telegram.error.BadRequest: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
butlarr  | 2024-06-19 08:43:42.129 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '13']
butlarr  | 2024-06-19 08:43:42.130 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:42.130 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:42.130 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:42.131 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:42.885 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '12']
butlarr  | 2024-06-19 08:43:42.886 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:42.886 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:42.886 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:42.887 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:47.384 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '11']
butlarr  | 2024-06-19 08:43:47.384 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:47.385 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:47.385 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:47.385 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:48.100 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '12']
butlarr  | 2024-06-19 08:43:48.100 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:48.100 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:48.100 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:48.100 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:53.687 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '11']
butlarr  | 2024-06-19 08:43:53.687 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:53.688 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:53.688 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:53.689 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:55.348 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '10']
butlarr  | 2024-06-19 08:43:55.348 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:55.349 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:55.350 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:55.350 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:43:56.508 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '9']
butlarr  | 2024-06-19 08:43:56.508 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:43:56.508 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:43:56.508 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:43:56.509 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
butlarr  | 2024-06-19 08:44:00.719 | DEBUG    | butlarr.tg_handler:handler:74 - Received callback: ['series', 'queue', '8']
butlarr  | 2024-06-19 08:44:00.719 | DEBUG    | butlarr.tg_handler:handle_callback:194 - Subcallback - Executing queue (clbk_queue)
butlarr  | 2024-06-19 08:44:00.720 | DEBUG    | butlarr.database:_get_con_cur:31 - Database connection established [/app/data/db.sqlite].
butlarr  | 2024-06-19 08:44:00.720 | DEBUG    | butlarr.database:_execute_query:69 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(7488221386,)]
butlarr  | 2024-06-19 08:44:00.720 | DEBUG    | butlarr.database:get_auth_level:122 - Query result for user lookup: {'id': 7488221386, 'username': 'Bernhard König', 'auth_level': 3}
 
```

**Comment by TrimVis** [comment]
This error is expected, but I'm now properly catching it :)
With the next feature release, I will update the docker image
